### PR TITLE
Refactoring and unittests

### PR DESCRIPTION
**Pull request by frdwrd**
~~Placeholder PR for ongoing work.~~

- [X] Refactor Protocol
- [X] Start linting with flake8
- [X] Layout and start unit tests
- [X] Write more unit tests
- [x] More linting!
- [X] Reincorporate old integration tests
~~- [ ] Write regtest scripts~~
- [x] setup tox or similar testrunner
- [x] Refactor DB to avoid instantiating on import
- [X] Figure out if existing tests a) work, b) belong as e2e tests
~~- [ ] Remove side effects from existing tests~~

**Notes:**
~~It's hard to tell if I've broken anything, as I'm still struggling with the regtest setups for bitcoind and zcashd. The vast majority of changes are style, but with the Protocol refactor in particular it's possible I missed something.~~ Updated in next comment.

I refactored Protocol to be an object. This prevents it from instantiating RPC objects on import, and makes testing much easier.  You no longer have to run bitcoind and zcashd with appropriate conf files to run unit tests.

~~I've removed the existing tests from test_cli.py. They should go back in in the future, as integration and end-to-end tests, once there's a good solution for spinning up environments.~~ Moved my tests to a new unit test folder and brought back the original `test_cli.py`.

I implemented unit tests for and added an error case to the `find_role` function in cli.py, because it was easy. Harder tests soon. >.>

I've done a significant amount of linting using flake8 (specifically linter-flake8 in Atom) on the files I've touched. Linting notes:

-  wildcards are replaced by package imports, so that the location of a function is explicit. E.g. `utils.save()` instead of `save()`.
- there are a few styled comments in utils.py that I left intact.
- there is a large console output block in cli that should either be broken up, or added to an ignore list.

### CODE REVIEW

**Comment by frdwrd** [comment]
Tested with bitcoind and zcashd running on regtest locally. Seems to verify that the protocol refactor is working as intended.

Steps I took:
1. Install zcashd & bitcoind
2. Create `~/.bitcoin/bitcoin.conf` and `~/.zcash/zcash.conf` (see below)
3. Run `zcashd` and `bitcoind`
4. Run `bitcoin-cli getnewaddress` and `zcash-cli getnewaddress` twice each
5. Update `xcat/xcatconf.py` with my addresses (and accidentally commit it).
6. Follow the instructions in `README.md` for buyer and seller.

Example conf file:
```
regtest=1
server=1
rpcuser=test
rpcpassword=test
rpcport=8333
```

**Comment by frdwrd** [comment]
Note to self:

`unittest` runs tests alphabetically. In `test_cli.py`, `test_fundsell` relies on the side effects of `test_newtrade`. It looks for the transaction `test_newtrade` created in the database. So the first time you run the tests on a new install, `test_fundsell` will fail (because it runs before `test_newtrade`). However, because `test_newtrade` then completes successfully, writing to the db in the process, `test_fundsell` will succeed when you run the tests again.

Steps to reproduce:
1. `rm -rf /tmp/xcatDB`
2. `python3 xcat/tests/test_cli.py`

**Comment by frdwrd** [comment]
there are a few places where I commented out lines that seemed to be doing nothing. Am I missing something here? Example:

https://github.com/zcash-hackworks/zbxcat/pull/29/files#diff-97a331ee019c5470d71ac01def0e4900R60

**Comment by frdwrd** [comment]
Can now run tests and flake8 using `tox`. Coverage reports in xml and html are generated and stored in `coverage/`. 

Currently `xcat/tests/test.py` is excluded. It looks severely outdated.

**Comment by frdwrd** [comment]
This is in a state where it can be reviewed. :+1:

**Comment by arcalinea** [comment]
Thanks, the improvements to the tests is much needed! 

I would prefer if you separated out the changes to the other files into a separate PR, but I looked through them all and it looks fine to merge. Next time :)

The lines you commented out which were doing nothing can be deleted, this code has been through several versions so there was some dead code.

**Comment by frdwrd** [comment]
> I would prefer if you separated out the changes to the other files into a separate PR, but I looked through them all and it looks fine to merge.

Will do :+1:

**Pull request merged**
